### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nucleartide** [nucleartide/UnityBits#18]
1. [ ] Dependency management
    1. [ ] Editor injection
    2. [ ] Service location
    3. [ ] Dependency injection
    4. [ ] Which one do I use?
2. [ ] Communication between entities
3. [ ] ScriptableObjects
4. [ ] File structure conventions
5. [ ] Prefabs
6. [ ] Autoformat
7. [ ] Unity Test Tools
8. [ ] Ship it
    1. [ ] Unity Cloud Build
    2. [ ] Continuous deployment
    3. [ ] itch.io

**Comment by nucleartide** [comment]
woah this is awesome https://itch.io/blog/178/get-ready-for-ludum-dare-38

**Comment by nucleartide** [comment]
from leafo's blog post:

1. game design + mechanics
2. Game intro & instructions
3. Player movement
4. Enemy AI
5. Levels
6. Graphics
7. Sound effects and music

**Comment by nucleartide** [comment]
overall, lots of interesting things to try. need to think about intro + timelapse + automatic CI builds. CI doesn't sound too important tbh.
